# name: API Test CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK 21
#         uses: actions/setup-java@v2
#         with:
#           java-version: '21'
#           distribution: 'temurin'

#       - name: Install dependencies
#         run: mvn install

#       - name: Run tests
#         run: mvn test

#       - name: Upload test results
#         if: always()
#         uses: actions/upload-artifact@v3
#         with:
#           name: allure-results
#           path: target/allure-results


name: API Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3  # Updated to v3 to use Node 20
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

      - name: Generate Allure Report
        if: success()
        run: |
          wget -qO- https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz | tar -zx -C /opt/
          export PATH=$PATH:/opt/allure-2.20.1/bin
          allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
